### ISSUE TITLE
start web error

### ISSUE THREAD

**Issue by digger-yu** [yijixiuxin/chanlun-pro#8]
Traceback (most recent call last):
  File "D:\git\chanlun-pro\web\chanlun_chart\app.py", line 15, in <module>
    from app import create_app
  File "D:\git\chanlun-pro\web\chanlun_chart\app\__init__.py", line 33, in <module>
    from chanlun.cl_utils import (
  File "D:\git\chanlun-pro\src\chanlun\cl_utils.py", line 3, in <module>
    from chanlun.exchange import exchange
  File "D:\git\chanlun-pro\src\chanlun\exchange\__init__.py", line 5, in <module>
    from chanlun.exchange.exchange_tdx import ExchangeTDX
  File "D:\git\chanlun-pro\src\chanlun\exchange\exchange_tdx.py", line 17, in <module>
    from chanlun.file_db import FileCacheDB
  File "D:\git\chanlun-pro\src\chanlun\file_db.py", line 13, in <module>
    from chanlun import cl
  File "D:\git\chanlun-pro\src\chanlun\cl.py", line 2, in <module>
    from pyarmor_runtime_005445 import __pyarmor__
  File "D:\git\chanlun-pro\src\pyarmor_runtime_005445\__init__.py", line 49, in <module>
    __pyarmor__ = __pyarmor__().__pyarmor__
  File "D:\git\chanlun-pro\src\pyarmor_runtime_005445\__init__.py", line 48, in __pyarmor__
    return __import__(name, globals(), locals(), ['__pyarmor__'], level=1)
RuntimeError: missing license key to run the script (1:10606)
missing license key to run the script (1:10606)
出现异常，按回车键退出Traceback (most recent call last):
  File "D:\git\chanlun-pro\web\chanlun_chart\app.py", line 15, in <module>
    from app import create_app
  File "D:\git\chanlun-pro\web\chanlun_chart\app\__init__.py", line 33, in <module>
    from chanlun.cl_utils import (
  File "D:\git\chanlun-pro\src\chanlun\cl_utils.py", line 3, in <module>
    from chanlun.exchange import exchange
  File "D:\git\chanlun-pro\src\chanlun\exchange\__init__.py", line 5, in <module>
    from chanlun.exchange.exchange_tdx import ExchangeTDX
  File "D:\git\chanlun-pro\src\chanlun\exchange\exchange_tdx.py", line 17, in <module>
    from chanlun.file_db import FileCacheDB
  File "D:\git\chanlun-pro\src\chanlun\file_db.py", line 13, in <module>
    from chanlun import cl
  File "D:\git\chanlun-pro\src\chanlun\cl.py", line 2, in <module>
    from pyarmor_runtime_005445 import __pyarmor__
  File "D:\git\chanlun-pro\src\pyarmor_runtime_005445\__init__.py", line 49, in <module>
    __pyarmor__ = __pyarmor__().__pyarmor__
  File "D:\git\chanlun-pro\src\pyarmor_runtime_005445\__init__.py", line 48, in __pyarmor__
    return __import__(name, globals(), locals(), ['__pyarmor__'], level=1)
RuntimeError: missing license key to run the script (1:10606)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\git\chanlun-pro\web\chanlun_chart\app.py", line 20, in <module>
    input("出现异常，按回车键退出")
AttributeError: 'filter' object has no attribute 'readline'

(chanlun) D:\git\chanlun-pro\web\chanlun_chart>

**Comment by mzywl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
